language: php
php:
  - 5.6
  - 7.0
  - hhvm

install:
  - cp .env.example .env
  - composer install --prefer-dist --no-interaction

script:
  - phpunit --coverage-text
  - vendor/bin/phpdoccheck -d src
  - vendor/bin/phpcpd --ansi src
  - vendor/bin/phpcs --standard=psr2 --colors src
  - vendor/bin/phpmd src text phpmd.xml
  - vendor/bin/phploc --ansi src